version: "3"
services:
  node:
    tty: true
    stdin_open: true
    container_name: "monitor-service"
    build: .
    env_file:
      - ./.env
    depends_on:
      - mongo
    ports:
      - 80:3000
    user: "node:node"
    volumes:
      - ./:/code
  mongo:
    image: "mongo:3.4"
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
